# Generated by Django 2.1.5 on 2019-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoControl',
            fields=[
                ('nit_acceso', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_personal', models.CharField(max_length=20)),
                ('apellido_personal', models.CharField(max_length=20)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=10)),
                ('foto', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'acceso_control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_dep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dep', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_muni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_muni', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosVotos',
            fields=[
                ('nit_user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'usuarios_votos',
                'managed': False,
            },
        ),
    ]
